# Generated by Django 5.2.6 on 2025-10-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Plan to Watch', 'Plan to Watch')], max_length=20),
        ),
    ]
