# Generated by Django 5.2.6 on 2025-10-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movies_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
