# Generated by Django 5.2.6 on 2025-10-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movies_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='movies/'),
        ),
    ]
